# Generated by Django 4.2.25 on 2025-11-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_merge_20251020_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalgraderdetail',
            name='queue_key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='externalgraderdetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pulled', 'Pulled'), ('retired', 'Retired'), ('failed', 'Failed'), ('retry', 'Retry')], default='pending', max_length=20),
        ),
    ]
