# Generated by Django 4.2.17 on 2025-03-14 22:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import submissions.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_externalgraderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file', models.FileField(max_length=512, upload_to=submissions.models.submission_file_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission_queue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                       related_name='files', to='submissions.externalgraderdetail')),
            ],
            options={
                'indexes': [models.Index(fields=['submission_queue', 'uid'], name='submissions_submiss_b1d4b0_idx')],
            },
        ),
    ]
