# Generated by Django 4.2.17 on 2025-01-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submissionqueuerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionqueuerecord',
            name='grader_reply',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissionqueuerecord',
            name='pullkey',
            field=models.CharField(default='c88826cd-d65c-41ca-847b-54f1809f5bc8', max_length=128),
            preserve_default=False,
        ),
    ]
