# Generated by Django 4.2.19 on 2025-04-04 16:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import submissions.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_externalgraderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file', models.FileField(max_length=512, upload_to=submissions.models.submission_file_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('external_grader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                      related_name='files', to='submissions.externalgraderdetail')),
            ],
            options={
                'indexes': [models.Index(fields=['external_grader', 'uid'], name='submissions_externa_657c60_idx')],
            },
        ),
    ]
