# Generated by Django 4.2.17 on 2025-01-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submissionqueuerecord_grader_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionqueuerecord',
            name='grader_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionqueuerecord',
            name='pullkey',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
