# Generated by Django 4.2.19 on 2025-05-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submissionfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalgraderdetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'),
                                            ('pulled', 'Pulled'), ('retired', 'Retired'), ('failed', 'Failed'),
                                            ('retry', 'Retry')], default='pending', max_length=20),
        ),
    ]
