# Generated by Django 4.2.17 on 2025-03-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submissionfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalgraderdetail',
            name='queue_key',
            field=models.CharField(default='cc24f8c5-2331-450f-aab8-b0d2df0c8a48', max_length=128),
            preserve_default=False,
        ),
    ]
