# Generated by Django 5.2 on 2025-10-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submissionfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalgraderdetail',
            name='queue_key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='externalgraderdetail',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('pulled', 'Pulled'),
                    ('retired', 'Retired'),
                    ('failed', 'Failed'),
                    ('retry', 'Retry')
                    ], default='pending', max_length=20
                ),
        ),
    ]
