# Generated by Django (merge migration)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submissionfile'),
        ('submissions', '0006_mariadb_uuid_conversion'),
    ]

    operations = [
    ]
