# Generated by Django 4.2.19 on 2025-05-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_alter_externalgraderdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalgraderdetail',
            name='queue_key',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
