# Generated by Django 4.2.17 on 2025-02-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_alter_submissionqueuerecord_grader_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionqueuerecord',
            name='grader_file_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='submissionqueuerecord',
            name='points_possible',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
