# Generated by Django 4.2.17 on 2025-02-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_submissionqueuerecord_grader_file_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubmissionQueueRecord',
            new_name='ExternalGraderDetail',
        ),
        migrations.RenameIndex(
            model_name='externalgraderdetail',
            new_name='submissions_queue_n_fbabd8_idx',
            old_name='submissions_queue_n_05eba7_idx',
        ),
    ]
