name: Check Reserved Keywords

on:
  - pull_request

jobs:
  check-reserved-keywords:
    name: Check Reserved Keywords
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install uv
      uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v6.5.0
      with:
        enable-cache: true
        python-version: "3.12"

    - name: Install CI dependencies
      run: uv sync --group ci

    - name: Check Keywords
      run: uv run tox -e check_keywords
